import os


LINODE_ACCESS_TOKEN = os.getenv("LINODE_ACCESS_TOKEN")

FIREWALL_ID = os.getenv("FIREWALL_ID")

INSTANCE_LABEL = os.getenv("INSTANCE_LABEL")

POST_OPERATION_NODE_LABELS = os.getenv("POST_OPERATION_NODE_LABELS")
